default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: bruno
  password: '[ 09 osbruno ]'

development:
  <<: *default
  database: auth_app_development

test:
  <<: *default
  database: auth_app_test<%= ENV['TEST_ENV_NUMBER'] %>
